### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by Tom1155** [ChrisTechs/PitHelper#1]
I dont know why, but my game every time crash.. I have latest version of Java. Can u help me with that?

**Comment by Tom1155** [comment]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

**Comment by ChrisTechs** [comment]
This mod depends on essentials
Make sure you have essentials [https://essential.gg/download](url)
Download the 1.8.9 forge jar and add it to your mods folder

**Comment by Tom1155** [comment]
yes, thanks that was the problem <3
